import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        elevated: '#1A1A24',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-secondary': '#003824',
        'surface-tint': '#c0c1ff',
        'on-tertiary-container': '#452000',
        'on-tertiary': '#4f2500',
        tertiary: '#ffb783',
        'text-secondary': '#8B8B9E',
        'on-background': '#e4e1e9',
        'text-muted': '#4A4A5E',
        'inverse-surface': '#e4e1e9',
        'surface-container-highest': '#35343a',
        'on-secondary-container': '#00311f',
        'on-primary-container': '#0d0096',
        'secondary-fixed': '#6ffbbe',
        'on-error': '#690005',
        'secondary-fixed-dim': '#4edea3',
        'surface-container-high': '#2a292f',
        'surface-bright': '#39383e',
        'surface-container-low': '#1b1b20',
        'primary-container': '#8083ff',
        'on-surface': '#e4e1e9',
        'primary-fixed': '#e1e0ff',
        'surface-dim': '#131318',
        danger: '#F43F5E',
        warning: '#F59E0B',
        'inverse-on-surface': '#303036',
        surface: '#111118',
        'inverse-primary': '#494bd6',
        primary: '#c0c1ff',
        'border-base': '#2A2A38',
        'surface-container': '#1f1f25',
        'on-surface-variant': '#c7c4d7',
        'surface-variant': '#35343a',
        'tertiary-container': '#d97721',
        'text-primary': '#F1F1F3',
        'error-container': '#93000a',
        'outline-variant': '#464554',
        'on-tertiary-fixed-variant': '#703700',
        'surface-container-lowest': '#0e0e13',
        'on-secondary-fixed': '#002113',
        'on-primary': '#1000a9',
        'on-tertiary-fixed': '#301400',
        'on-error-container': '#ffdad6',
        'on-primary-fixed-variant': '#2f2ebe',
        secondary: '#4edea3',
        background: '#131318',
        outline: '#908fa0',
        'secondary-container': '#00a572',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-secondary-fixed-variant': '#005236',
        error: '#ffb4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        unit: '4px',
        'margin-desktop': '48px',
        'container-max': '1280px',
        gutter: '24px',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'monospace'],
        'display-lg': ['Sora', 'sans-serif'],
        'body-md': ['Sora', 'sans-serif'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-lg': ['Sora', 'sans-serif'],
        'body-sm': ['Sora', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
      animation: {
        'pulse-dot': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
