"""
Test Manager Agent with Campaign Input Data
Reads data from campaign_input.json and generates strategic plan using LLM
"""

import sys
from pathlib import Path
from dotenv import load_dotenv
import json

load_dotenv()
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.state import CampaignState
from agents.manager import manager_agent


def main():
    # Read campaign input from JSON file
    print("\n" + "="*100)
    print("📋 LOADING CAMPAIGN INPUT DATA")
    print("="*100)
    
    input_file = Path(__file__).parent / "inputs" / "campaign_input.json"
    
    with open(input_file, 'r') as f:
        campaign_data = json.load(f)
    
    print("\n✅ Campaign Input Loaded:")
    print(f"   Campaign Name: {campaign_data['campaign_name']}")
    print(f"   Brand: {campaign_data['brand_name']}")
    print(f"   Industry: {campaign_data['industry']}")
    print(f"   Goal: {campaign_data['primary_goal']}")
    print(f"   Audience: {campaign_data['target_audience']}")
    print(f"   Voice: {campaign_data['brand_voice']}")
    
    # Create campaign state
    state = CampaignState(**campaign_data)
    
    # Run Manager Agent
    print("\n" + "="*100)
    print("🚀 RUNNING MANAGER AGENT WITH LLM")
    print("="*100)
    
    result_state = manager_agent(state)
    
    # Display Results
    print("\n" + "="*100)
    print("📊 FINAL RESULTS")
    print("="*100)
    
    plan = json.loads(result_state.manager_output)
    
    print("\n✅ Manager Plan Generated Successfully!")
    print(f"\nStatus: {result_state.status}")
    print("\n📍 Recommended Channels:")
    for i, channel in enumerate(plan['channels'], 1):
        print(f"   {i}. {channel}")
    
    print("\n📦 Recommended Deliverables:")
    for i, deliverable in enumerate(plan['deliverables'], 1):
        print(f"   {i}. {deliverable}")
    
    print("\n💾 Full Output:")
    print(json.dumps(plan, indent=2))
    
    print("\n" + "="*100)
    print("✅ MANAGER AGENT COMPLETED - OUTPUT GENERATED BY LLM BASED ON PROMPT")
    print("="*100)


if __name__ == "__main__":
    main()
