"""
Test Research Agent with Campaign Input Data
Runs both Manager and Research agents in sequence
"""

import sys
from pathlib import Path
from dotenv import load_dotenv
import json

load_dotenv()
sys.path.insert(0, str(Path(__file__).parent.parent))

import utils.logger  # noqa: F401
from agents.state import CampaignState
from agents.manager import manager_agent
from agents.research import research_agent


def main():
    # Read campaign input from JSON file
    print("\n" + "="*100)
    print("📋 LOADING CAMPAIGN INPUT DATA")
    print("="*100)
    
    input_file = Path(__file__).parent / "inputs" / "campaign_input.json"
    
    with open(input_file, 'r') as f:
        campaign_data = json.load(f)
    
    print("\n✅ Campaign Input Loaded:")
    print(f"   Campaign Name: {campaign_data['campaign_name']}")
    print(f"   Brand: {campaign_data['brand_name']}")
    print(f"   Industry: {campaign_data['industry']}")
    print(f"   Goal: {campaign_data['primary_goal']}")
    print(f"   Audience: {campaign_data['target_audience']}")
    print(f"   Voice: {campaign_data['brand_voice']}")
    
    # Create campaign state
    state = CampaignState(**campaign_data)
    state.brief = f"Marketing campaign for {campaign_data['brand_name']} targeting {campaign_data['target_audience']}"
    
    # ========== STEP 1: RUN MANAGER AGENT ==========
    print("\n" + "="*100)
    print("🚀 STEP 1: RUNNING MANAGER AGENT")
    print("="*100)
    
    state = manager_agent(state)
    
    manager_plan = json.loads(state.manager_output)
    print("\n✅ Manager Plan Created:")
    print(f"   Channels: {', '.join(manager_plan['channels'])}")
    print(f"   Deliverables: {', '.join(manager_plan['deliverables'])}")
    
    # ========== STEP 2: RUN RESEARCH AGENT ==========
    print("\n" + "="*100)
    print("🔍 STEP 2: RUNNING RESEARCH AGENT")
    print("="*100)
    
    state = research_agent(state)
    
    # Display Results
    print("\n" + "="*100)
    print("📊 FINAL RESEARCH RESULTS")
    print("="*100)
    
    research_output = json.loads(state.research_output)
    
    print("\n✅ Research Completed Successfully!")
    print(f"\nStatus: {state.status}")
    
    print("\n📊 MARKET ANALYSIS:")
    ma = research_output['market_analysis']
    print(f"   TAM: {ma['total_addressable_market']}")
    print(f"   Growth Rate: {ma['growth_rate']}")
    print("   Market Trends:")
    for trend in ma['market_trends']:
        print(f"     • {trend}")
    
    print("\n🏆 COMPETITOR ANALYSIS:")
    ca = research_output['competitor_analysis']
    print(f"   Top Competitors: {', '.join(ca['top_competitors'])}")
    print("   Differentiation Opportunity:")
    print(f"     {ca['differentiation_opportunity']}")
    
    print("\n👥 AUDIENCE INSIGHTS:")
    ai = research_output['audience_insights']
    print("   Pain Points:")
    for pain in ai['pain_points']:
        print(f"     • {pain}")
    print("   Motivations:")
    for motivation in ai['motivations']:
        print(f"     • {motivation}")
    print(f"   Preferred Channels: {', '.join(ai['preferred_channels'])}")
    
    print("\n💡 MARKET OPPORTUNITIES:")
    for opp in research_output['market_opportunities']:
        print(f"   • {opp}")
    
    print("\n🎯 RECOMMENDED APPROACH:")
    print(f"   {research_output['recommended_approach']}")
    
    print("\n💾 Full Research Output:")
    print(json.dumps(research_output, indent=2))
    
    print("\n" + "="*100)
    print("✅ RESEARCH AGENT COMPLETED - OUTPUT GENERATED BY LLM BASED ON PROMPT")
    print("="*100)


if __name__ == "__main__":
    main()
