"""
RESEARCH AGENT - Market Analysis, Competitive Intel & Customized Insights

Role: Market Researcher / Competitive Analyst / Audience Intelligence

INPUT (From Manager Agent + State):
  FROM state:
    ✅ brief: User's campaign brief (context for research insights)
  
  FROM manager_output (fields needed for research):
    ✅ campaign_name: Campaign identifier
    ✅ brand_name: Brand identifier
    ✅ industry: Industry context for market analysis
    ✅ primary_goal: Campaign goal for audience insights
    ✅ target_audience: Detailed audience for customization
    ✅ brand_voice: Tone for personalization
    ✅ channels: Recommended channels from manager
    ✅ deliverables: Recommended deliverables from manager

OUTPUT (5 Fields - JSON - Research foundation for Strategy & Copywriter):
  1. market_analysis: TAM, growth_rate, market_trends (LLM-generated by industry)
  2. competitor_analysis: top_competitors, differentiation_opportunity (LLM-generated)
  3. audience_insights: pain_points, motivations, preferred_channels (LLM-customized)
  4. market_opportunities: Industry-specific growth opportunities (LLM-generated)
  5. recommended_approach: Strategic approach (LLM-personalized)

HOW IT WORKS:
1. Extract fields from manager_output and state
2. Load research prompt template
3. Send campaign context to LLM for analysis
4. LLM generates customized research insights
5. Return 5 fields for Strategy Agent

KEY PRINCIPLE:
Research = AI-Powered Market Intelligence
- LLM analyzes industry, competitors, and audience
- Generates context-aware, specific insights
- No hardcoded data - fully dynamic research
- Uses prompt template from utils/prompts/research_prompt.txt
"""

import logging
logger = logging.getLogger(__name__)

import sys
from pathlib import Path
import json
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Add project root to path so imports work
sys.path.insert(0, str(Path(__file__).parent.parent))

from agents.state import CampaignState
from llm import get_llm_client
from llm.factory import get_current_llm_config
from utils.prompt_loader import load_prompt, load_split_prompt
from utils.error_handler import safe_llm_call
from utils.llm_cache import make_key, get as cache_get, set as cache_set
from schemas import ResearchOutput
from services.search_service import search_web
import datetime


# ==================== RESEARCH AGENT FUNCTION ====================

def research_agent(state: CampaignState) -> CampaignState:
    """
    Research Agent - Market Analysis & Insights (LLM-Powered)
    
    Args:
        state: CampaignState with manager_output and brief
    
    Returns:
        Updated CampaignState with research_output (5 fields JSON)
    
    Process:
    1. Extract manager output and brief from state
    2. Load research prompt template
    3. Send to LLM for comprehensive market research
    4. Parse LLM response to get 5 research fields
    5. Update state with research output
    """
    
    logger.info("\n" + "=" * 80)
    logger.info("🔍 RESEARCH AGENT ACTIVATED")
    logger.info("=" * 80)
    
    # ========== STEP 1: READ MANAGER OUTPUT ==========
    logger.info("\n[STEP 1] Reading manager output from state...")
    logger.info("-" * 80)
    
    if not state.manager_output:
        raise ValueError("No manager_output found in state")
    
    try:
        manager_data = json.loads(state.manager_output)
    except Exception as e:
        raise ValueError(f"Failed to parse manager_output: {e}")
    
    campaign_name = manager_data.get('campaign_name', 'Unknown Campaign')
    brand_name = manager_data.get('brand_name', 'Unknown Brand')
    industry = manager_data.get('industry', 'other')
    primary_goal = manager_data.get('primary_goal', 'awareness')
    target_audience = manager_data.get('target_audience', 'general audience')
    brand_voice = manager_data.get('brand_voice', 'professional')
    channels = manager_data.get('channels', [])
    deliverables = manager_data.get('deliverables', [])
    brief = state.brief or "No brief provided"
    
    logger.info(f"✓ Campaign: {campaign_name}")
    logger.info(f"✓ Brand: {brand_name}")
    logger.info(f"✓ Industry: {industry}")
    logger.info(f"✓ Goal: {primary_goal}")
    logger.info(f"✓ Target Audience: {target_audience[:60]}...")
    logger.info(f"✓ Brand Voice: {brand_voice}")
    logger.info(f"✓ Channels: {', '.join(channels)}")
    logger.info(f"✓ Brief: {brief[:60] if brief != 'No brief provided' else 'N/A'}...")
    
    # ========== STEP 2: CONDUCT RESEARCH WITH LLM ==========
    logger.info("\n[STEP 2] Conducting market research with LLM...")
    logger.info("-" * 80)
    logger.info("🔬 Analyzing market landscape with AI...")
    
    # Initialize LLM client
    llm = get_llm_client()
    llm_config = get_current_llm_config()
    tavily_api_key = (llm_config.get("tavily_api_key") or "").strip() or None
    
    # Format human revision feedback if research is targeted for revision
    is_human_revision = bool(
        (state.human_feedback and state.human_revision_target == "research") or
        (state.status == "research_revision_required")
    )
    human_feedback_section = ""
    if is_human_revision:
        existing_research_section = ""
        if state.research_output:
            existing_research_section = (
                "\n\nEXISTING RESEARCH (your previous output — preserve ALL unchanged fields exactly):\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                f"{state.research_output}\n"
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            )
        feedback_text = state.human_feedback or "AI Reviewer requested revision."
        human_feedback_section = (
            "\n" + "="*80 + "\n"
            "⚠️ HUMAN REVISION FEEDBACK — SURGICAL EDIT MODE:\n"
            "You are in REVISION mode. The user has requested a specific change below.\n"
            "CRITICAL REVISION RULES — MUST FOLLOW:\n"
            "  1. READ the user feedback carefully and identify ONLY which field(s) need changing.\n"
            "  2. ONLY modify what the user explicitly asked for. Nothing else.\n"
            "  3. DO NOT output any fields that you are not changing. Exclude them entirely from your JSON output (Sparse JSON Patch).\n"
            "  4. Only output the specific fields that need to be updated based on the feedback.\n"
            f"User Feedback: \"{feedback_text}\"\n"
            + "="*80
            + existing_research_section
        )

    additional_context = getattr(state, "client_memory_context", None) or "None (No additional context)"

    # Load research prompt and format with campaign data
    system_prompt, prompt = load_split_prompt(
        "research",
        campaign_name=campaign_name,
        brand_name=brand_name,
        industry=industry,
        primary_goal=primary_goal,
        target_audience=target_audience,
        brand_voice=brand_voice,
        brief=brief,
        additional_context=additional_context,
        channels=', '.join(channels),
        deliverables=', '.join(deliverables),
        human_feedback_section=human_feedback_section
    )
    
    # LiteRAG Real-Time Web Search
    logger.info("   Executing LiteRAG real-time web search...")
    current_year = datetime.date.today().year
    product_name = getattr(state, 'product_name', brand_name) or brand_name
    
    # If the product name looks like a placeholder or a new brand, we search generic industry trends to ensure rich results.
    # Otherwise, we search for the specific brand.
    is_placeholder_brand = product_name.lower().strip() in [
        "lune & coast", "hot_wears", "new brand", "brand name", "my brand", "placeholder", "test brand", "lune and coast", "hot wears"
    ]
    
    # Incorporate additional_info context to ensure search relevance
    # additional_info comes from state.brief or additional_context stored by the manager
    additional_info = getattr(state, "additional_info", None) or (
        manager_data.get("additional_info") or manager_data.get("brief") or ""
    )
    extra_keywords = ""
    if additional_info and len(str(additional_info).strip()) > 0:
        kw_words = [w for w in str(additional_info).strip().split() if len(w) > 3][:4]
        if kw_words:
            extra_keywords = " " + " ".join(kw_words)

    # Clean audience keywords (take first 3 words to avoid query over-constraining)
    clean_audience = " ".join(target_audience.strip().split()[:3]) if target_audience else ""

    # ── Universal Entity-Preserving Search Query Normalization ──
    # Clean brackets/parentheses into clean whitespace so search engines treat all tokens naturally
    # without choking on syntax operators (e.g. "Haridwar University (HU Roorkee)" -> "Haridwar University HU Roorkee")
    import re
    clean_product_name = re.sub(r'[\(\)\[\]\{\}]', ' ', product_name)
    clean_product_name = " ".join(clean_product_name.split()).strip()

    if is_placeholder_brand or not product_name:
        logger.info(f"   ℹ️ Generic search target ('{product_name}') — running industry market trends query for '{industry}'")
        query_1 = f"{industry} market trends growth statistics {current_year}".strip()
        query_2 = f"{industry} top direct competitors market landscape analysis".strip()
        query_3 = f"{industry} customer pain points complaints reddit reviews".strip()
        query_4 = f"{industry} top converting ad visual hooks angles {current_year}".strip()
        query_5 = f"{brand_name} official website company background value proposition".strip()
    else:
        ind_term = f"{industry} " if (industry and industry.lower() != 'other') else ""
        query_1 = f"{ind_term}market trends statistics {current_year}".strip()
        query_2 = f"{clean_product_name} {ind_term}direct peer competitors alternatives similar brands".strip()
        query_3 = f"{clean_product_name} {ind_term}customer pain points complaints reddit".strip()
        query_4 = f"{industry} top converting ad visual hooks angles {current_year}".strip()
        query_5 = f"official website {clean_product_name} brand positioning value proposition".strip()

    logger.info(f"   🔎 Tavily Market Query: '{query_1}'")
    logger.info(f"   🔎 Tavily Competitor Query: '{query_2}'")
    logger.info(f"   🔎 Tavily Customer Pain Query: '{query_3}'")
    logger.info(f"   🔎 Tavily Ad Hooks Query: '{query_4}'")
    logger.info(f"   🔎 Tavily Official Website Query: '{query_5}'")

    import concurrent.futures

    # Execute all 5 multi-vertical Tavily searches + Brand DNA scraper concurrently in parallel
    logger.info("   🚀 Executing 5 multi-vertical Tavily searches + Brand DNA scraper concurrently in parallel...")
    parallel_start = datetime.datetime.now()

    def _safe_fetch_dna():
        try:
            from services.brand_dna_service import fetch_brand_website_dna
            return fetch_brand_website_dna(brand_name=brand_name, timeout_seconds=5.0)
        except Exception as _dna_err:
            logger.warning("   ⚠️ Brand DNA extraction non-blocking error: %s", _dna_err)
            return None

    with concurrent.futures.ThreadPoolExecutor(max_workers=6) as executor:
        f1 = executor.submit(search_web, query_1, redis_client=None, max_results=4, api_key=tavily_api_key)
        f2 = executor.submit(search_web, query_2, redis_client=None, max_results=4, api_key=tavily_api_key)
        f3 = executor.submit(search_web, query_3, redis_client=None, max_results=3, api_key=tavily_api_key)
        f4 = executor.submit(search_web, query_4, redis_client=None, max_results=3, api_key=tavily_api_key)
        f5 = executor.submit(search_web, query_5, redis_client=None, max_results=3, api_key=tavily_api_key)
        f_dna = executor.submit(_safe_fetch_dna)

        result_1 = f1.result()
        result_2 = f2.result()
        result_3 = f3.result()
        result_4 = f4.result()
        result_5 = f5.result()
        dna_data = f_dna.result()

    elapsed_s = (datetime.datetime.now() - parallel_start).total_seconds()
    total_snippets = len(result_1.snippets) + len(result_2.snippets) + len(result_3.snippets) + len(result_4.snippets) + len(result_5.snippets)
    logger.info(f"   ⚡ LiteRAG & Brand DNA parallel execution completed in {elapsed_s:.2f}s ({total_snippets} total snippets retrieved)")

    # Build context — ONLY inject if snippets actually exist, wrapped in semantic XML tags
    context_parts = []

    if result_1.success and result_1.snippets:
        context_parts.append(
            "<real_time_market_context>\n" +
            "\n".join(f"- {s}" for s in result_1.snippets) +
            "\n</real_time_market_context>"
        )

    if result_2.success and result_2.snippets:
        context_parts.append(
            "<competitor_vulnerabilities_context>\n" +
            "\n".join(f"- {s}" for s in result_2.snippets) +
            "\n</competitor_vulnerabilities_context>"
        )

    if result_3.success and result_3.snippets:
        context_parts.append(
            "<customer_voice_reddit_pain_points>\n" +
            "\n".join(f"- {s}" for s in result_3.snippets) +
            "\n</customer_voice_reddit_pain_points>"
        )

    if result_4.success and result_4.snippets:
        context_parts.append(
            "<high_converting_ad_hooks_context>\n" +
            "\n".join(f"- {s}" for s in result_4.snippets) +
            "\n</high_converting_ad_hooks_context>"
        )

    if result_5.success and result_5.snippets:
        context_parts.append(
            "<official_website_search_context>\n" +
            "\n".join(f"- {s}" for s in result_5.snippets) +
            "\n</official_website_search_context>"
        )

    # Autonomous Brand DNA Ingestion Integration
    if dna_data and dna_data.get("extracted_hero_text"):
        state.brand_dna = dna_data
        logger.info("   ✅ Fetched Brand DNA successfully")
    elif result_5.success and result_5.snippets:
        # ── Tavily Brand DNA Fallback ─────────────────────────────────────────
        # Direct website crawl returned None (timeout / blocked / non-HTML content).
        # Synthesize Brand DNA from the Tavily official website search (query_5) which
        # ran in parallel and always has results. This prevents the downstream reviewer
        # from flagging 'Brand DNA field missing' for sites that block crawlers.
        tavily_source_url = result_5.sources[0].url if result_5.sources else f"https://{brand_name.lower().replace(' ', '')}.com"
        tavily_hero_text = "\n".join(f"- {s}" for s in result_5.snippets[:5])
        dna_data = {
            "source_url": tavily_source_url,
            "extracted_hero_text": tavily_hero_text,
            "crawled_at_host": brand_name,
            "source": "tavily_fallback",  # Distinguishes from direct crawl
        }
        state.brand_dna = dna_data
        logger.info("   ✅ Brand DNA synthesized from Tavily fallback (direct crawl unavailable): %s", tavily_source_url)
    else:
        # ── Synthetic Brand DNA Safety Net ────────────────────────────────────
        # Both direct web crawl AND Tavily search failed/timed out.
        # Synthesize Brand DNA from campaign metadata so state.brand_dna is NEVER None.
        clean_brand_domain = f"https://www.{brand_name.lower().replace(' ', '')}.com"
        synth_hero_text = (
            f"Official brand representation for {brand_name} in the {industry} sector. "
            f"Targeting {target_audience}. Campaign focus: {brief[:200]}"
        )
        dna_data = {
            "source_url": clean_brand_domain,
            "extracted_hero_text": synth_hero_text,
            "crawled_at_host": brand_name,
            "source": "metadata_synthetic_fallback",
        }
        state.brand_dna = dna_data
        logger.info("   ✅ Brand DNA synthesized from campaign metadata (network/crawler unavailable): %s", clean_brand_domain)

    # Use Brand DNA context builder for research prompt
    from utils.brand_dna_context import build_brand_dna_context
    dna_context = build_brand_dna_context(state.brand_dna, purpose="research", max_tokens=1500)
    if dna_context.text:
        context_parts.append(
            "<official_brand_dna_context>\n" +
            f"Source URL: {state.brand_dna.get('source_url', 'Unknown')}\n" +
            f"{dna_context.text}\n" +
            "</official_brand_dna_context>"
        )
        logger.info("   ✅ Integrated budgeted Brand DNA into Research Agent context")


    # Collect all sources for UI
    all_sources = []

    # Include Official Brand DNA Website Source at the top of the sources list
    if getattr(state, "brand_dna", None) and isinstance(state.brand_dna, dict) and state.brand_dna.get("source_url"):
        src_url = state.brand_dna.get("source_url")
        try:
            from urllib.parse import urlparse
            dom = urlparse(src_url).netloc or brand_name
        except Exception:
            dom = brand_name
        all_sources.append({
            "url": src_url,
            "title": f"Official Brand Website ({brand_name})",
            "domain": dom,
            "snippet": state.brand_dna.get("extracted_hero_text", "")[:240],
            "query_type": "official_website"
        })
        logger.info("   🌐 Added official website source to UI sources list: %s", src_url)

    for result, qtype in [
        (result_1, "market"),
        (result_2, "competitor"),
        (result_3, "customer_voice"),
        (result_4, "ad_hooks"),
        (result_5, "official_website"),
    ]:
        if result.success:
            for src in result.sources:
                all_sources.append({
                    "url": src.url,
                    "title": src.title,
                    "domain": src.domain,
                    "snippet": src.snippet,
                    "query_type": qtype
                })

    if context_parts:
        # CRITICAL: Prepend context BEFORE the research instructions (not append after).
        # Reason: When token budget truncation fires, `slice_context_to_budget` uses head/tail
        # slicing. If context is appended last, truncation trims the INSTRUCTIONS (TAM, schema)
        # which are mission-critical. By prepending context, any overflow trims the grounding
        # snippets (recoverable) and keeps the instructions (non-negotiable) intact at the end.
        context_block = "\n\n".join(context_parts)
        prompt = context_block + "\n\n" + prompt
    
    logger.info("   Querying LLM with structured output...")

    # Revision runs: lower temperature avoids regenerating unchanged fields;
    # higher token budget compensates for the extra existing-output context
    revision_temperature = 0.0 if is_human_revision else 0.7
    revision_max_tokens = 8192

    if is_human_revision:
        logger.info(f"   [REVISION MODE] temperature={revision_temperature}, max_tokens={revision_max_tokens}")

    # Cache-aware LLM call
    cache_key = make_key("Research", prompt=prompt, temperature=revision_temperature, max_tokens=revision_max_tokens)
    cached = cache_get(cache_key)
    if cached is not None:
        logger.info("📦 Cache hit — using cached Research response")
        research_data = ResearchOutput(**cached)
    else:
        research_data, state = safe_llm_call(
            state,
            "Research",
            lambda: llm.generate_structured(prompt, ResearchOutput, system_prompt=system_prompt, temperature=revision_temperature, max_tokens=revision_max_tokens)
        )
        if research_data is not None:
            cache_set(cache_key, research_data.model_dump())

    if is_human_revision and state.research_output and research_data is not None:
        logger.info("\n[MERGE] Executing Semantic Delta Patching deep merge for Research...")
        try:
            from utils.delta_merger import deep_merge_dicts
            previous_dict = json.loads(state.research_output)
            merged_dict = deep_merge_dicts(previous_dict, research_data.model_dump(exclude_unset=True))
            research_data = ResearchOutput(**merged_dict)
            logger.info("   ✅ Semantic Delta Patch merged cleanly over previous research_output")
        except Exception as exc:
            logger.warning(f"   ⚠️ Research delta merge warning: {exc} — preserving current research output")
    
    if research_data is None:
        return state  # Error already logged in state

    # Attach Brand DNA and LiteRAG sources to the output
    research_data.brand_dna = getattr(state, "brand_dna", None)
    research_data.literas_sources = all_sources
    research_data.tavily_sources = all_sources
    research_data.search_status = {
        "provider": "tavily",
        "enabled": bool(tavily_api_key or os.getenv("TAVILY_API_KEY")),
        "total_sources": len(all_sources),
        "total_snippets": total_snippets,
        "queries": [
            {
                "query_type": "market",
                "query": result_1.query,
                "success": result_1.success,
                "sources": len(result_1.sources),
                "snippets": len(result_1.snippets),
                "error": result_1.error_message,
            },
            {
                "query_type": "competitor",
                "query": result_2.query,
                "success": result_2.success,
                "sources": len(result_2.sources),
                "snippets": len(result_2.snippets),
                "error": result_2.error_message,
            },
        ],
    }
    
    # ========== STEP 3: DISPLAY FINDINGS ==========
    logger.info("\n[STEP 3] Research insights generated!")
    logger.info("-" * 80)
    logger.info("✅ Research insights generated by LLM!")
    
    logger.info("\n📊 Market Analysis:")
    logger.info(f"   TAM: {research_data.market_analysis.total_addressable_market}")
    logger.info(f"   Growth: {research_data.market_analysis.growth_rate}")
    logger.info(f"   Trends: {', '.join(research_data.market_analysis.market_trends[:2])}...")
    
    logger.info("\n🏆 Competitor Analysis:")
    logger.info(f"   Top Competitors: {', '.join(research_data.competitor_analysis.top_competitors)}")
    logger.info(f"   Differentiation: {research_data.competitor_analysis.differentiation_opportunity[:60]}...")
    
    logger.info("\n👥 Audience Insights:")
    logger.info(f"   Pain Points: {', '.join(research_data.audience_insights.pain_points[:3])}...")
    logger.info(f"   Motivations: {', '.join(research_data.audience_insights.motivations[:2])}...")
    logger.info(f"   Channels: {', '.join(research_data.audience_insights.preferred_channels)}")
    
    logger.info("\n💡 Market Opportunities:")
    for opp in research_data.market_opportunities[:2]:
        logger.info(f"   • {opp}")
    
    logger.info("\n🎯 Recommended Approach:")
    logger.info(f"   {research_data.recommended_approach[:80]}...")
    
    # ========== STEP 4: WRITE TO STATE ==========
    logger.info("\n[STEP 4] Writing to state...")
    logger.info("-" * 80)
    
    research_output_json = research_data.model_dump_json(indent=2)
    
    # Mutate CampaignIntelligenceObject (CIO) directly in state
    cio_dict = dict(state.campaign_intelligence_object or {})
    cio_dict["campaign_name"] = cio_dict.get("campaign_name") or campaign_name
    cio_dict["brand_name"] = cio_dict.get("brand_name") or brand_name
    cio_dict["industry"] = cio_dict.get("industry") or industry
    cio_dict["primary_goal"] = cio_dict.get("primary_goal") or primary_goal
    cio_dict["target_icp"] = cio_dict.get("target_icp") or target_audience
    pains = (research_data.audience_insights.pain_points if research_data.audience_insights else []) or []
    objections = (getattr(research_data.audience_insights, "buyer_objections", None) or []) if research_data.audience_insights else []
    if not objections and pains:
        objections = [f"Risk related to {pains[0]}"]
    cio_dict["primary_pain_points"] = pains
    cio_dict["buyer_objections"] = objections
    state.campaign_intelligence_object = cio_dict
    
    state.research_output = research_output_json
    state.status = "research_complete"
    
    logger.info("✅ State updated:")
    logger.info(f"   research_output: {len(research_output_json)} characters")
    logger.info(f"   campaign_intelligence_object updated with {len(pains)} pain points & {len(objections)} objections")
    logger.info(f"   status: {state.status}")
    
    logger.info("\n" + "=" * 80)
    logger.info("✅ RESEARCH AGENT COMPLETE")
    logger.info("=" * 80)
    
    return state


# ==================== MAIN EXECUTION ====================

if __name__ == "__main__":
    logger.info("\n" + "="*80)
    logger.info("⚠️  This is the agent module file.")
    logger.info("    To test the Research Agent, run: python examples/run_research.py")
    logger.info("    To customize input, edit: examples/inputs/campaign_input.json")
    logger.info("="*80)
